name: 环境检测

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: 构建 Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - name: 安装 AArch64 交叉编译库
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: 环境检查
        run: |
             find /usr -path "/usr/local" -prune -o -name "libstdc++.a" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "libgcc.a" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crtbeginT.o" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crtend.o" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crt1.o" -print 2>/dev/null


