name: 环境检测

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    name: 构建 Linux aarch64
    runs-on: ubuntu-latest
    steps:
      - name: 安装 AArch64 交叉编译库
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          
          TEMP_DIR=$(mktemp -d)
          cd "$TEMP_DIR"
          wget http://ports.ubuntu.com/pool/main/z/zlib/zlib1g_1.3.dfsg+really1.3.1-1ubuntu2_arm64.deb
          wget http://ports.ubuntu.com/pool/main/z/zlib/zlib1g-dev_1.3.dfsg+really1.3.1-1ubuntu2_arm64.deb

          dpkg-deb -x zlib1g_1.3.dfsg+really1.3.1-1ubuntu2_arm64.deb zlib1g
          dpkg-deb -x zlib1g-dev_1.3.dfsg+really1.3.1-1ubuntu2_arm64.deb zlib1g-dev

          sudo cp -v zlib1g-dev/usr/include/*.h /usr/aarch64-linux-gnu/include/
          sudo cp -v zlib1g/usr/lib/aarch64-linux-gnu/libz.so.* /usr/aarch64-linux-gnu/lib/
          sudo cp -v zlib1g-dev/usr/lib/aarch64-linux-gnu/libz.a /usr/aarch64-linux-gnu/lib/

          cd /usr/aarch64-linux-gnu/lib
          sudo ln -sf libz.so.1.3 libz.so.1
          sudo ln -sf libz.so.1 libz.so

          cd /
          rm -rf "$TEMP_DIR"
      - name: 环境检查
        run: |
             find /usr -path "/usr/local" -prune -o -name "libstdc++.a" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "libgcc.a" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crtbeginT.o" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crtend.o" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "crt1.o" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "libz.a" -print 2>/dev/null
             find /usr -path "/usr/local" -prune -o -name "zlib.h" -print 2>/dev/null
